server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matrix
    username: root
    password: Xnn1234#
    driver-class-name: com.mysql.cj.jdbc.Driver

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50
    threadNamePrefix: nanaThread-


logging:
  config: classpath:logback-spring.xml
  level.org.springframework.boot.autoconfigure: ERROR
  level:
    com:
      tuya:
        ci:
          testbook:
            core:
              dao: DEBUG

debug: true

sso:
  redirect: false
