server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matrix
    username: root
    password: Xnn1234#
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-spring.xml
  level.org.springframework.boot.autoconfigure: ERROR
  level:
    com:
      tuya:
        ci:
          testbook:
            core:
              dao: DEBUG

debug: true

sso:
  redirect: false
